version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    command: npm run migrate:up & npm run start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    depends_on:
      - db
    environment:
      MYSQL_SCHEMA: sbf
      NODE_ENV: production
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  db:
    container_name: 'mysql-sbf'
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=sbf
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - TZ=America/Sao_Paulo
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
