openapi: '3.0.2'
info:
  version: 1.0.0
  title: CURRENCY
  description: Serviço para converter preço para moeda
  contact:
    name: API Support
    email: 'superte@teste.com'

servers:
  - description: Desenvolvimento
    url: http://localhost:3000/v1


tags:
  - name: Currencies
    description: >
      As `currencies` são as moedas que podem ser utilizada para converter preços dos produtos para atender clientes que desejam pagar em suas moedas locais.
paths:
  /currency:
    post:
      tags:
        - Currencies
      summary: Criar moeda
      description: |
        Cria um nova moeda para ser utilizada para conversão


      requestBody:
        content:
          application/json:
            schema:
              required:
                - name
                - value
              properties:
                value:
                  type: number
                  example: 5.30
                name:
                  type: string
                  example: 'USD'


      responses:
        201:
          description: Moeda criada com sucesso
          content:
            application/json:
              schema:
                properties:
                  currencyId:
                    $ref: '#/components/schemas/CurrencyId'
        400:
          $ref: '#/components/responses/BadRequest'

    get:
      tags:
        - Currencies
      summary: Listar moedas
      description: Lista todas as moedas existentes
      responses:
        200:
          description: Dados das moedas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: '4985562c-429f-436f-985a-6d90c55ff6d0'
                    name:
                      type: string
                      example: 'EUR'
                    value:
                      type: number
                      example: 5.78
                    createdAt:
                      type: string
                      example: '2022-07-19 18:58:54'
                    updatedAt:
                      type: string
                      example: '2022-07-19 18:58:54'

        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'


  /currency/{id}:
    patch:
      tags:
        - Currencies
      summary: Atualizar moeda por id
      description: Atualizar uma moeda armazenada pelo id
      requestBody:
        content:
          application/json:
            schema:
              required:
                - value
              properties:
                value:
                  type: number
                  example: 5.30
      parameters:
        - name: id
          in: path
          description: ID da moeda
          required: true
          schema:
            $ref: '#/components/schemas/CurrencyId'
      responses:
        200:
          description: Resposta com os dados da moeda
          content:
            application/json:
              schema:
                properties:
                  name:
                    type: string
                    example: "USD"
                  value:
                    type: number
                    example: 5.98
        404:
          $ref: '#/components/responses/NotFound'

  /currency/amount:
    post:
      tags:
        - Currencies
      summary: Converter valores para as moedas salvas
      description: Converte o valor informado para as moedas atualmentes salvas
      requestBody:
        content:
          application/json:
            schema:
              required:
                - amount
              properties:
                amount:
                  type: number
                  example: 5.30
      responses:
        200:
          description: Resposta com a lista dos valores
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: "USD"
                    price:
                      type: number
                      example: 255.72
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    CurrencyId:
      type: string
      format: UUID-V4
      description: ID da moeda
      example: 'dbdb6da1-4594-4ad6-b870-3021b927525d'

  responses:
    BadRequest:
      description: Requisição inválida
      content:
        'application/json':
          schema:
            properties:
              code:
                description: Código do erro
                type: string
                example: 'BAD_REQUEST'
              message:
                description: Mensagem de erro
                type: string
                example: 'Invalid request params'
              details:
                description: Detalhes do erro
                type: array
                example:
                  - message: '"body.account.branch" is not allowed to be empty'

    NotFound:
      description: Recurso não encontrado
      content:
        'application/json':
          schema:
            properties:
              code:
                description: Código do erro
                type: string
                example: NOT_FOUND
              message:
                description: Mensagem de erro
                type: string
                example: 'Resource not found'
              details:
                description: Detalhes do erro
                type: array
                example:
                  - message: 'The requested resource was not found'

    InternalServerError:
      description: Erro interno do servidor
      content:
        'application/json':
          schema:
            properties:
              code:
                description: Código do erro
                type: string
                example: 'INTERNAL_SERVER_ERROR'
              message:
                description: Mensagem de erro
                type: string
                example: 'Failed to create a currency'
              details:
                description: Detalhes do erro
                type: array
                example:
                  - message: 'Unexpected error to create a currency'
